import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Profile from "@/components/layout/profile";
import Contacts from "@/components/layout/users";
import { AuthProvider } from "@/contexts/authContext";
import { PostProvider } from "@/contexts/postContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <PostProvider>
            {children}
          </PostProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
